/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyAwesomeCounter {
        /**
          * The actual count
         */
        "count": number;
        "invert": () => Promise<void>;
    }
}
declare global {
    interface HTMLMyAwesomeCounterElement extends Components.MyAwesomeCounter, HTMLStencilElement {
    }
    var HTMLMyAwesomeCounterElement: {
        prototype: HTMLMyAwesomeCounterElement;
        new (): HTMLMyAwesomeCounterElement;
    };
    interface HTMLElementTagNameMap {
        "my-awesome-counter": HTMLMyAwesomeCounterElement;
    }
}
declare namespace LocalJSX {
    interface MyAwesomeCounter {
        /**
          * The actual count
         */
        "count"?: number;
    }
    interface IntrinsicElements {
        "my-awesome-counter": MyAwesomeCounter;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-awesome-counter": LocalJSX.MyAwesomeCounter & JSXBase.HTMLAttributes<HTMLMyAwesomeCounterElement>;
        }
    }
}
